# Config file for automatic testing at travis-ci.org

language: python

python: 3.7
cache:
    directories:
        - "$HOME/.cargo"
        - rust/target
env:
    PATH:$HOME/.cargo/bin:$PATH
    proba:
        secure: "YSPBV6v3B3HUf9na1WPumCMl2j6cQ9l+xHGKl0XB5/iiyCQ9CGs+1hJTqjFDLAaA2Ko83Uly5dxaKjjgKRJwTUxZByVMAnntk64OEN5b6Pupaf8iy6V/oVweFyXeKfVUwXgQvECzlrxdKIpZOThouFShXEKwQ+S82ADePjY6bJb97d8+YiX8aDAnlEVpNaGBaukaeeMoiqHsc+ebMBC5Sr3mpeqEuE4lDf6s6e/bN8Shygs7gykuip24Od7cNtndPkapIFP2NQEHw9XFcOe/zsXCZnagDMFBgCJuvwtjzNFfRXRyZnqilbEXK92TkmAPytbJp4PgUd75RW6hr22Bd1bx2TfvAiWILqckcM/CcaCqaZmKaOBO0dJJMsrDBfqH+mieSsQ7wjHg7LawmN7ueSogx3wqOH1N880FiV7/KHzO0PDX16kKiI+H2G4jQ9/RBo9vgfQr6ycMHSvF6FGD3GicnmlWJLzH7XLShtQ+lfK6cJYzhpYXLOclIAC5nYHCT7HIzd/H9vd/R0KcUFrCPVDliUpEWAGw3K1ipK3/ok349B02TPgGLD7ASiJa3TraK+zCSlKeIr7D9MCV80zlUo3JPujvrsaWisqGQiwPbJjX3etRis8fLdvrI8aoCmVTZEKYc/S8z9x5DvhJdVXfdFpdzLZ8czq8dcvZiX/ZZhY="

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sh rust-installer.sh
  
# Command to run tests, e.g. python setup.py test
script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - echo $proba
  - ls $HOME/.cargo/bin
  - python build_wheel.py

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: vitalije
  password:
    secure:  "k4nVOlvPjeB8i4PpSIJAcGLRQBHN5Qlxo36AGoFdAnX11qnIoXdbAZAZSbJJCUmqRXoCa56aRMTItQpq9W6epcECkEwoiu29L2Be6REksrFTFeuahCEAOGWtM2Ynpk07Rf6AxNth70J+IowYpsixZ7fLS2Q02jUOYYnpytRF+icT5+CsmuKGdOXCLvlIUe9geY+JnUEOKsfVgr2e5uOZHItxxmHZx0BB5RyGcZogUmKiTuAxpB8EfudNucyaRLFFtIfmZonx0wCZJ+RqbA040XLJHAWdoEuL2P7HPIqbklMYgOfk6579EVzHSJXa/N6wKaDXeHb8SWpWX/1iy4ef6AW1VEipqJxIZEBiFT26zfVcXY7HboQ5xjskml4y/V1XOdYZZ4lYL9uZ4kxt9cSEy0wvpLOSdksZRS2jgmvmaLIlPZD8x1V3T6PnuhH7aLIBNMcuAXI0xyQR1xHArK3sb9OKsx4krLn8Zq9x4+QmLNN+Gk5g2Hb3Sa6vQL3LEB0dk6SF1QHVBqpDaYr4QL57xqxsfjFq3PaleDTGvd2Pno5h3d5TIwgGf72j0IEhCpLqESBvNMbucxg4cH1ZqmUoaRQJOHdtOz9BoG8QnhHVUxG1iSoMUi8rCiDPYGGfLrE+7B5pZVG0Z7cqHxsU/Y0N47GTz9Gutzx5ibYnfAr+2+4="
  on:
    tags: true
    repo: vitalije/mini_leo
    python: 3.7
