version: 0.1.{build}
image: Visual Studio 2015
shallow_clone: true
clone_depth: 5
environment:
  PYTHON_VERSION: 3.7
init:
  - set PYTHON=C:\PYTHON3.7
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
