version: 0.1.{build}
image: Visual Studio 2015
shallow_clone: true
clone_depth: 5
environment:
  PYTHON_VERSION: 3.7
  RUSTUP_INSTALLER_ADDRES_X64: https://win.rustup.rs/x86_64
  RUSTUP_INSTALLER_ADDRES_X32: https://win.rustup.rs/i686
init:
  - set PYTHON=C:\PYTHON37-x64
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - dir C:\users\
  - python --version
install:
  - pip install requests
  - python -c "import requests;s=requests.get('https://win.rustup.rs/x86_64').content;out=open('rustup-inst.exe','wb');out.write(s)"
  - rustup-inst.exe --help
platform: x64
build_script:
   - python -V
