version: 0.1.{build}
image: Visual Studio 2015
shallow_clone: true
clone_depth: 5
environment:
  PYTHON_VERSION: 3.7
init:
  - set PYTHON=C:\PYTHON37-x64
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - ECHO %PATH%
  - python --version
platform: x64
build_script:
   - python -V
