version: 0.1.{build}
image: Visual Studio 2015
shallow_clone: true
clone_depth: 5
environment:
  PYTHON_VERSION: 3.7
  RUSTUP_INSTALLER_ADDRES_X64: https://win.rustup.rs/x86_64
  RUSTUP_INSTALLER_ADDRES_X32: https://win.rustup.rs/i686
cache:
  - '%USERPROFILE%\.cargo\'
  - 'rust\target\'
init:
  - set PYTHON=C:\PYTHON37-x64
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - dir C:\users\
  - python --version
install:
  - pip install requests
  - python -c "import requests;s=requests.get('https://win.rustup.rs/x86_64').content;out=open('rustup-init.exe','wb');out.write(s)"
  - rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal --default-toolchain nightly
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
platform: x64
build_script:
   - chdir rust
   - cargo build --lib --release
   - dir target\release
